-- Auto-generated by scripts/generate-seed-reference-data.ts. Do not edit by hand.
-- Global reference data seeded on `supabase db reset` for local dev / CI.

-- wow_classes (11 rows)
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('fb944151-f11d-4c40-a5ba-134b3b06ca13', 'Warrior', '#C79C6E') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('8275e59b-b397-44c5-be4e-2dc4852d1139', 'Paladin', '#F58CBA') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('3ba4ab59-035b-4f05-a702-1e2a1bbdda91', 'Hunter', '#ABD473') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('784bf92f-a10f-4039-82e8-9a8021841959', 'Rogue', '#FFF569') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('3c0b0a13-2627-4e30-8196-f5f02bfe6970', 'Priest', '#FFFFFF') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('e554945e-c73d-493a-8911-8d31d59209f8', 'Shaman', '#0070DE') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('40188a47-fb93-43a6-9750-c5eff14bb8ad', 'Mage', '#69CCF0') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('5dcd3b64-c8e7-4601-a6b1-f8117fb9f3e9', 'Warlock', '#9482C9') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('028cf7a5-1678-4062-8247-3c764fd8d883', 'Druid', '#FF7D0A') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('59c1024c-0c18-4d3c-b983-a6944b17aa04', 'Death Knight', '#C41E3A') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.wow_classes ("id", "name", "color_hex") VALUES ('bdd1aac0-fa2d-4fd7-aa0c-db88db84c992', 'Monk', '#00FF98') ON CONFLICT (id) DO NOTHING;

-- class_specs (23 rows)
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('798ea7ae-6e80-40cb-9717-152fd51a180c', 'fb944151-f11d-4c40-a5ba-134b3b06ca13', 'Protection', '2026-01-09T10:35:36.666241+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('9e7f102f-4ec6-44e9-93ca-de05702bc6c9', 'fb944151-f11d-4c40-a5ba-134b3b06ca13', 'Arms/Fury', '2026-01-09T10:35:36.806816+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('5f06f3d6-e70a-4561-957c-f8182b2a37b7', '8275e59b-b397-44c5-be4e-2dc4852d1139', 'Holy', '2026-01-09T10:35:36.914648+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('c7ce3658-f943-49bf-afed-bbddae2c4bea', '8275e59b-b397-44c5-be4e-2dc4852d1139', 'Retribution', '2026-01-09T10:35:37.023218+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('ecbbee63-64c9-48fa-817e-a23efef596cb', '8275e59b-b397-44c5-be4e-2dc4852d1139', 'Protection', '2026-01-09T10:35:37.134815+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('acbad6e3-7c86-467e-ab0b-024dbb5b4ad6', '3ba4ab59-035b-4f05-a702-1e2a1bbdda91', 'Hunter', '2026-01-09T10:35:37.252789+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('566c2026-2431-4147-a14d-4150fcd7f7b3', '784bf92f-a10f-4039-82e8-9a8021841959', 'Rogue', '2026-01-09T10:35:37.360396+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('3c4f8872-a9ba-411c-80dc-218c38f3e905', '3c0b0a13-2627-4e30-8196-f5f02bfe6970', 'Holy/Disc', '2026-01-09T10:35:37.510549+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('1257f9ff-cafe-40e0-aec4-7840940e8a28', '3c0b0a13-2627-4e30-8196-f5f02bfe6970', 'Shadow', '2026-01-09T10:35:37.628305+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('d3cddca1-cb09-4640-9fd5-fdac96a7261a', 'e554945e-c73d-493a-8911-8d31d59209f8', 'Restoration', '2026-01-09T10:35:37.763896+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('eda8bde7-ce76-4a3d-87a8-3a26459e35b3', 'e554945e-c73d-493a-8911-8d31d59209f8', 'Elemental', '2026-01-09T10:35:37.883741+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('52071ceb-5e54-43c9-b327-ce92964e3a11', 'e554945e-c73d-493a-8911-8d31d59209f8', 'Enhancement', '2026-01-09T10:35:37.990178+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('321922b5-47a5-4c9c-80ae-dbd1efd2f575', '40188a47-fb93-43a6-9750-c5eff14bb8ad', 'Mage', '2026-01-09T10:35:38.096481+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('9a431f1d-fd2a-476a-8ede-3689861020b6', '5dcd3b64-c8e7-4601-a6b1-f8117fb9f3e9', 'Warlock', '2026-01-09T10:35:38.205451+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('255eff4a-d049-4a05-8fc8-a6ed6b7b6268', '028cf7a5-1678-4062-8247-3c764fd8d883', 'Restoration', '2026-01-09T10:35:38.31082+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('52b90666-50c1-40cb-b786-5b571a5e7d25', '028cf7a5-1678-4062-8247-3c764fd8d883', 'Feral', '2026-01-09T10:35:38.422192+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('368d30a5-db02-4e46-8964-804486e54272', '028cf7a5-1678-4062-8247-3c764fd8d883', 'Balance', '2026-01-09T10:35:38.547558+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('d4822992-80bf-4133-a871-4b22ff70d7ab', '59c1024c-0c18-4d3c-b983-a6944b17aa04', 'Blood', '2026-03-10T09:02:25.167532+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('1c92bf9d-480d-4156-b4a7-28d817fa2132', '59c1024c-0c18-4d3c-b983-a6944b17aa04', 'Frost/Unholy', '2026-03-10T09:02:25.167532+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('0a4ee206-f74c-472e-aaa3-962156fd8ba6', 'bdd1aac0-fa2d-4fd7-aa0c-db88db84c992', 'Brewmaster', '2026-03-10T09:02:25.167532+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('7b5d5f1a-1c94-40c7-89f1-3b3881ea1543', 'bdd1aac0-fa2d-4fd7-aa0c-db88db84c992', 'Windwalker', '2026-03-10T09:02:25.167532+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('2ac14f5d-39cb-43c6-88d4-a5f13feae98e', 'bdd1aac0-fa2d-4fd7-aa0c-db88db84c992', 'Mistweaver', '2026-03-10T09:02:25.167532+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.class_specs ("id", "class_id", "name", "created_at") VALUES ('9f4d82e8-1d1f-4550-8476-c9b677bf2e5a', '028cf7a5-1678-4062-8247-3c764fd8d883', 'Guardian', '2026-03-11T05:44:38.921032+00:00') ON CONFLICT (id) DO NOTHING;
