/**
 * Token Copy Counts
 *
 * Maps a token's Wowhead item ID to how many copies a raider may list: the
 * number of distinct gear slots it can be turned in for. Read via
 * maxCopiesForItem() in domain/loot/slot-capacity.ts; the count applies once
 * in main spec and once again in off-spec (domain/loot/item-copies.ts).
 *
 * Rule: for each class, the distinct equip slots of the rewards that class
 * can get, max over classes. Reward ids the wow-classic-items package does not
 * know are dropped for Classic, TBC and Wrath; a reward that is itself a
 * catalog token counts that token's slots. Ids absent from this map mean 1.
 *
 * Auto-generated by scripts/fetch-token-copies.ts
 * Generated: 2026-10-01
 * Resolved: 322 of 322 tokens
 * No equippable reward (1 copy): 18705 Mature Black Dragon Sinew; 45038 Fragment of Val'anyr; 69815 Seething Cinder; 71141 Eternal Ember; 77952 Elementium Gem Cluster
 * Unresolved (1 copy): none
 */

export const TOKEN_MAX_COPIES: Record<number, number> = {
  20928: 2, // Qiraji Bindings of Command: Shoulder, Feet
  20932: 2, // Qiraji Bindings of Dominance: Shoulder, Feet
  21232: 3, // Imperial Qiraji Armaments: One-Hand, Shield, Ranged
  21237: 2, // Imperial Qiraji Regalia: One-Hand, Two-Hand
  47242: 5, // Trophy of the Crusade: Head, Shoulder, Chest, Legs, Hands
  47557: 5, // Regalia of the Grand Conqueror: Head, Shoulder, Chest, Legs, Hands
  47558: 5, // Regalia of the Grand Protector: Head, Shoulder, Chest, Legs, Hands
  47559: 5, // Regalia of the Grand Vanquisher: Head, Shoulder, Chest, Legs, Hands
  52025: 5, // Vanquisher's Mark of Sanctification: Head, Shoulder, Chest, Legs, Hands
  52026: 5, // Protector's Mark of Sanctification: Head, Shoulder, Chest, Legs, Hands
  52027: 5, // Conqueror's Mark of Sanctification: Head, Shoulder, Chest, Legs, Hands
  52028: 5, // Vanquisher's Mark of Sanctification (Heroic): Head, Shoulder, Chest, Legs, Hands
  52029: 5, // Protector's Mark of Sanctification (Heroic): Head, Shoulder, Chest, Legs, Hands
  52030: 5, // Conqueror's Mark of Sanctification (Heroic): Head, Shoulder, Chest, Legs, Hands
  105857: 5, // Essence of the Cursed Protector: Head, Shoulder, Chest, Legs, Hands
  105858: 5, // Essence of the Cursed Conqueror: Head, Shoulder, Chest, Legs, Hands
  105859: 5, // Essence of the Cursed Vanquisher: Head, Shoulder, Chest, Legs, Hands
  105866: 5, // Essence of the Cursed Protector (Heroic): Head, Shoulder, Chest, Legs, Hands
  105867: 5, // Essence of the Cursed Conqueror (Heroic): Head, Shoulder, Chest, Legs, Hands
  105868: 5, // Essence of the Cursed Vanquisher (Heroic): Head, Shoulder, Chest, Legs, Hands
}
