/**
 * Fetch Item Icons from Wowhead
 *
 * This script extracts all unique wowhead_ids from our raid data files,
 * fetches the icon names from Wowhead's tooltip API, and generates a mapping file.
 *
 * Usage: npx tsx scripts/fetch-item-icons.ts
 */

import * as fs from 'fs'
import * as path from 'path'

// Import all raid data
import { moltenCore, blackwingLair, onyxiasLair, zulGurub, ruinsOfAhnQiraj, templeOfAhnQiraj, naxxramas } from '../data/classic-wow-raids'
import { karazhan, gruulslair, magtheridonslair, serpentshrinecavern, tempestkeep, mounthyjal, blacktemple, sunwellplateau, zulaman } from '../data/tbc-raids'
import { wrathRaids } from '../data/wrath-raids'
import { cataRaids } from '../data/cata-raids'
import { mopRaids } from '../data/mop-raids'

interface IconMapping {
  [wowheadId: number]: string
}

type Expansion = 'classic' | 'tbc' | 'wrath' | 'cata' | 'mop'

// Extract all unique wowhead_ids from raids
function extractWowheadIds(): { id: number; name: string; expansion: Expansion }[] {
  const items: { id: number; name: string; expansion: Expansion }[] = []
  const seenIds = new Set<number>()

  function addRaids(raids: Array<{ bosses: Array<{ items: Array<{ wowhead_id: number; name: string }> }> }>, expansion: Expansion) {
    for (const raid of raids) {
      for (const boss of raid.bosses) {
        for (const item of boss.items) {
          if (!seenIds.has(item.wowhead_id)) {
            seenIds.add(item.wowhead_id)
            items.push({ id: item.wowhead_id, name: item.name, expansion })
          }
        }
      }
    }
  }

  // Classic raids
  addRaids([moltenCore, blackwingLair, onyxiasLair, zulGurub, ruinsOfAhnQiraj, templeOfAhnQiraj, naxxramas], 'classic')

  // TBC raids
  addRaids([karazhan, gruulslair, magtheridonslair, serpentshrinecavern, tempestkeep, mounthyjal, blacktemple, sunwellplateau, zulaman], 'tbc')

  // WotLK raids
  addRaids(wrathRaids, 'wrath')

  // Cata raids
  addRaids(cataRaids, 'cata')

  // MoP raids
  addRaids(mopRaids, 'mop')

  return items
}

// Fetch icon name from Wowhead tooltip API
async function fetchIconName(wowheadId: number, expansion: Expansion): Promise<string | null> {
  const url = `https://nether.wowhead.com/tooltip/item/${wowheadId}?dataEnv=1&locale=0`

  try {
    const response = await fetch(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
        'Accept': 'application/json',
      }
    })

    if (!response.ok) {
      console.error(`Failed to fetch ${wowheadId}: ${response.status}`)
      return null
    }

    const data = await response.json()
    return data.icon || null
  } catch (error) {
    console.error(`Error fetching ${wowheadId}:`, error)
    return null
  }
}

// Rate-limited batch fetching
async function fetchAllIcons(items: { id: number; name: string; expansion: Expansion }[]): Promise<IconMapping> {
  const mapping: IconMapping = {}
  const batchSize = 10
  const delayMs = 500 // 500ms between batches to be nice to Wowhead

  console.log(`Fetching icons for ${items.length} items...`)

  for (let i = 0; i < items.length; i += batchSize) {
    const batch = items.slice(i, i + batchSize)

    const results = await Promise.all(
      batch.map(async (item) => {
        const icon = await fetchIconName(item.id, item.expansion)
        return { id: item.id, icon, name: item.name }
      })
    )

    for (const result of results) {
      if (result.icon) {
        mapping[result.id] = result.icon
      } else {
        console.warn(`  No icon found for ${result.name} (${result.id})`)
      }
    }

    const progress = Math.min(i + batchSize, items.length)
    console.log(`  Progress: ${progress}/${items.length} (${Math.round(progress / items.length * 100)}%)`)

    if (i + batchSize < items.length) {
      await new Promise(resolve => setTimeout(resolve, delayMs))
    }
  }

  return mapping
}

// Generate the TypeScript mapping file
function generateMappingFile(mapping: IconMapping): string {
  const sortedEntries = Object.entries(mapping)
    .sort(([a], [b]) => Number(a) - Number(b))

  const lines = sortedEntries.map(([id, icon]) => `  ${id}: '${icon}'`)

  return `/**
 * Item Icon Mapping
 *
 * Maps Wowhead item IDs to their icon names.
 * Icons can be loaded from: https://wow.zamimg.com/images/wow/icons/{size}/{icon_name}.jpg
 * Sizes: small (18x18), medium (36x36), large (56x56)
 *
 * Auto-generated by scripts/fetch-item-icons.ts
 * Generated: ${new Date().toISOString().split('T')[0]}
 * Total items: ${sortedEntries.length}
 */

export const ITEM_ICONS: Record<number, string> = {
${lines.join(',\n')}
}

/**
 * Get the icon URL for an item
 */
export function getItemIconUrl(wowheadId: number, size: 'small' | 'medium' | 'large' = 'small'): string | null {
  const iconName = ITEM_ICONS[wowheadId]
  if (!iconName) return null
  return \`https://wow.zamimg.com/images/wow/icons/\${size}/\${iconName}.jpg\`
}

// Track which icons have been preloaded to avoid duplicate work
const preloadedIcons = new Set<string>()

/**
 * Preload icons for a list of items
 * This ensures icons are cached before they're displayed
 */
export function preloadItemIcons(wowheadIds: number[], size: 'small' | 'medium' | 'large' = 'small'): void {
  if (typeof window === 'undefined') return

  for (const id of wowheadIds) {
    const url = getItemIconUrl(id, size)
    if (url && !preloadedIcons.has(url)) {
      preloadedIcons.add(url)
      const img = new Image()
      img.src = url
    }
  }
}
`
}

async function main() {
  console.log('Extracting wowhead IDs from raid data...')
  const items = extractWowheadIds()
  console.log(`Found ${items.length} unique items`)

  // Check if we have an existing mapping to use as cache
  const outputPath = path.join(__dirname, '../data/item-icons.ts')
  let existingMapping: IconMapping = {}

  if (fs.existsSync(outputPath)) {
    try {
      const existing = await import('../data/item-icons')
      existingMapping = existing.ITEM_ICONS || {}
      console.log(`Loaded ${Object.keys(existingMapping).length} existing icons from cache`)
    } catch {
      console.log('No existing mapping found, fetching all icons')
    }
  }

  // Filter to only items we don't have icons for
  const itemsToFetch = items.filter(item => !existingMapping[item.id])

  if (itemsToFetch.length === 0) {
    console.log('All icons already cached!')
    return
  }

  console.log(`Need to fetch ${itemsToFetch.length} new icons`)

  const newMapping = await fetchAllIcons(itemsToFetch)
  const finalMapping = { ...existingMapping, ...newMapping }

  console.log(`\nTotal icons: ${Object.keys(finalMapping).length}`)

  const content = generateMappingFile(finalMapping)
  fs.writeFileSync(outputPath, content)
  console.log(`\nSaved to ${outputPath}`)
}

main().catch(console.error)
