/**
 * Generate supabase/seed.sql with global reference data.
 *
 * Reads the static, guild-independent reference tables from the linked prod
 * project and emits idempotent INSERTs into supabase/seed.sql, so a local
 * `supabase db reset` populates them automatically (the schema baseline has
 * no rows). Re-run this if the reference data changes.
 *
 * Usage: npx tsx scripts/generate-seed-reference-data.ts
 */
import { createClient } from '@supabase/supabase-js'
import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

// Always read PROD creds from .env.local (do not honor a local override here).
const envFile = readFileSync(resolve(process.cwd(), '.env.local'), 'utf8')
const env = (k: string) =>
  (envFile.match(new RegExp(`^${k}=(.*)$`, 'm'))?.[1] || '').trim().replace(/^["']|["']$/g, '')
const db = createClient(env('NEXT_PUBLIC_SUPABASE_URL'), env('SUPABASE_SERVICE_ROLE_KEY'))

// Order matters: parents before children (class_specs.class_id -> wow_classes.id).
const TABLES = ['wow_classes', 'class_specs']

function sqlValue(v: unknown): string {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
  return `'${String(v).replace(/'/g, "''")}'`
}

async function main() {
  const out: string[] = [
    '-- Auto-generated by scripts/generate-seed-reference-data.ts. Do not edit by hand.',
    '-- Global reference data seeded on `supabase db reset` for local dev / CI.',
    '',
  ]

  for (const table of TABLES) {
    const { data, error } = await db.from(table).select('*')
    if (error) { console.error(`read ${table}:`, error.message); process.exit(1) }
    if (!data?.length) { console.warn(`${table}: 0 rows, skipping`); continue }

    const cols = Object.keys(data[0])
    out.push(`-- ${table} (${data.length} rows)`)
    for (const row of data) {
      const vals = cols.map(c => sqlValue((row as Record<string, unknown>)[c])).join(', ')
      out.push(`INSERT INTO public.${table} (${cols.map(c => `"${c}"`).join(', ')}) VALUES (${vals}) ON CONFLICT (id) DO NOTHING;`)
    }
    out.push('')
    console.log(`${table}: ${data.length} rows`)
  }

  writeFileSync(resolve(process.cwd(), 'supabase/seed.sql'), out.join('\n'))
  console.log('Wrote supabase/seed.sql')
}
main().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1) })
